AssignmentProject_UI/Models/DTOs/Request/LoginRequest.cs
namespace AssignmentProject_UI.Models.DTOs.Request
{
    public class LoginRequest
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

AssignmentProject_UI/Models/DTOs/Request/ProductInventoryRequest.cs
namespace AssignmentProject_UI.Models.DTOs.Request
{
    public class ProductInventoryRequest
    {
        public string InventoryType { get; set; }
        public string ProductId { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
        public string Brand { get; set; }
        public string Quantity { get; set; }
        public string Status { get; set; }
        public List<ProductImage> Images { get; set; } = new List<ProductImage>();
    }
    public class ProductImage
    {
        public string ImageID { get; set; }
        public string ImageBase64 { get; set; }
        public string Status { get; set; }
    }
}

AssignmentProject_UI/Models/DTOs/Response/GenericResponse.cs
namespace AssignmentProject_UI.Models.DTOs.Response
{
    public class GenericResponse
    {
        public bool isSuccess { get; set; }
        public string message { get; set; }
        public Object data { get; set; }
        public List<Error> errors { get; set; } = new List<Error>();
    }
    public class Error
    {
        public string errorMessage { get; set; }
        public int errorID { get; set; }
    }
}

AssignmentProject_UI/Models/DTOs/Response/LoginRequest.cs
namespace AssignmentProject_UI.Models.DTOs.Response
{
    public class LoginRequest
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

AssignmentProject_UI/Models/DTOs/Response/UserLoginResponse.cs
namespace AssignmentProject_UI.Models.DTOs.Response
{
    public class UserLoginResponse
    {
        public int userID { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userRole { get; set; }
        public string apiKey { get; set; }
    }
}

AssignmentProject_UI/Models/ErrorViewModel.cs
namespace AssignmentProject_UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AssignmentProject_UI/Controllers/HomeController.cs
using AssignmentProject_UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AssignmentProject_UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AssignmentProject_UI/Controllers/LoginController.cs
using AssignmentProject_UI.DataAccessLayer.Interface;
using AssignmentProject_UI.Models.DTOs.Request;
using AssignmentProject_UI.Models.DTOs.Response;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AssignmentProject_UI.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogin _login;
        private readonly IConfiguration _configuration;
        public LoginController(ILogin login, IConfiguration configuration) {
            _login = login;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckUserLogin([FromBody] LoginRequest model)
        {
            UserLoginResponse userLoginResponse = _login.CheckUserLogin(model);
            if(userLoginResponse != null)
            {
                if (!string.IsNullOrEmpty(userLoginResponse.apiKey))
                {
                    HttpContext.Session.SetString("ApiKey", userLoginResponse.apiKey);
                    HttpContext.Session.SetString("UserRole", userLoginResponse.userRole);
                }
                
            }
            return Ok(userLoginResponse);
        }
    }
}

AssignmentProject_UI/Controllers/ProductController.cs
using AssignmentProject_UI.DataAccessLayer.Interface;
using AssignmentProject_UI.Models.DTOs.Request;
using AssignmentProject_UI.Models.DTOs.Response;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net;
using System.Text;
using System.Text.Json;

namespace AssignmentProject_UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct _product;

        public ProductController(IProduct product)
        {
            _product = product;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Get()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct([FromBody] ProductInventoryRequest model)
        {
            GenericResponse genericResponse = new GenericResponse();
            string Apikey = HttpContext.Session.GetString("ApiKey");

            genericResponse = _product.ProductInventoryManagement(model, Apikey);
            return Ok(genericResponse);
        }
        [HttpPost]
        public IActionResult GetProductLists([FromBody] ProductInventoryRequest model)
        {
            GenericResponse genericResponse = new GenericResponse();
            string Apikey = HttpContext.Session.GetString("ApiKey");
            genericResponse = _product.ProductInventoryManagement(model, Apikey);
            return Ok(genericResponse);
        }
    }
}

AssignmentProject_UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AssignmentProject_UI/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssignmentProject_UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssignmentProject_UI.styles.css" asp-append-version="true" />

    <style>
        .divider:after,
.divider:before {
content: "";
flex: 1;
height: 1px;
background: #eee;
}
.h-custom {
height: calc(100% - 73px);
}
@@media (max-width: 450px) {
.h-custom {
height: 100%;
}
}
    </style>
</head>
<body>

    <section class="vh-100">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form>
                        <div class="form-outline mb-4">
                            <input type="email" id="txtEmail" class="form-control form-control-lg"
                                   placeholder="Enter a valid email address" />
                            <label class="form-label" for="form3Example3">Email address</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-3">
                            <input type="password" id="txtpassword" class="form-control form-control-lg"
                                   placeholder="Enter password" />
                            <label class="form-label" for="form3Example4">Password</label>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="button" onclick="return login();" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">
                                Login
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
            <!-- Copyright -->
            <div class="text-white mb-3 mb-md-0">
                Copyright © 2020. All rights reserved.
            </div>
            <!-- Copyright -->
            <!-- Right -->
            <div>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-google"></i>
                </a>
                <a href="#!" class="text-white">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </div>
            <!-- Right -->
        </div>
    </section>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
    function login(){
            var Email = $("#txtEmail").val();
            var Password = $("#txtpassword").val();

        var Obj = {
            Email: Email,
            Password: Password
        };
        alert("HI working");
            $.ajax({
                url: '@Url.Action("CheckUserLogin", "Login")',
                method: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(Obj),
                success: function (response) {
                    // Handle successful login
                    console.log(response);
                    if (response.apiKey != null) {
                        window.location.href = "/Product/Get";
                    } else {
                        alert("Invalid login details");
                        return false;
                    }
                    
                },
                error: function (xhr, status, error) {
                    // Handle login error
                    console.error(xhr.responseText);
                    alert('Login failed');
                }
            });
        return false;
    }    
    </script>
</body>
</html>

AssignmentProject_UI/Views/Product/Get.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Get";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-12">

            <h1 class="text-white mb-4">Apply for a job</h1>

            <div class="card" style="border-radius: 15px;">
                <div class="card-body">
                    <div class="row align-items-center py-3">
                        <div class="col-md-5 ps-5">
                            <h6 class="mb-0">Name</h6>  <input id="txtFilterName" type="text" class="form-control" />
                        </div>
                        <div class="col-md-5 pe-5">
                            <h6 class="mb-0">Brand</h6>  <input id="txtFilterBrand" type="text" class="form-control" />
                        </div>
                        <div class="col-md-2 pe-5">
                            <button type="button" id="btnSearch" class="btn btn-primary btn-sm" style="margin-bottom: -11px;">Search</button>
                        </div>
                    </div>
                    <div class="row align-items-center pt-4 pb-3">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Brand</th>
                                    <th scope="col">Status</th>
                                    @if (HttpContextAccessor.HttpContext.Session.GetString("UserRole") == "Admin")
                                    {
                                        <th scope="col">Action</th>
                                    }
                                </tr>
                            </thead>
                            <tbody id="productBodyList">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="updateProductModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update Product Details</h5>
                <button type="button" class="close" data-dismiss="modal" onclick="return CloseModal();" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col-xl-12">
                            <div class="card" style="border-radius: 15px;">
                                <div class="card-body">

                                    <div class="row align-items-center pt-4 pb-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Name</h6>

                                        </div>
                                        <div class="col-md-9 pe-5">

                                            <input id="txtName" type="text" class="form-control" />

                                        </div>
                                    </div>

                                    <hr class="mx-n3">

                                    <div class="row align-items-center py-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Amount</h6>

                                        </div>
                                        <div class="col-md-9 pe-5">

                                            <input id="txtAmount" type="text" class="form-control" />

                                        </div>
                                    </div>

                                    <hr class="mx-n3">

                                    <div class="row align-items-center py-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Quantity</h6>

                                        </div>
                                        <div class="col-md-9 pe-5">
                                            <input type="text" id="txtQuantity" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row align-items-center py-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Brand</h6>

                                        </div>
                                        <div class="col-md-9 pe-5">

                                            <input type="text" id="txtBrand" class="form-control" />

                                        </div>
                                    </div>
                                    <div class="row align-items-center py-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Status</h6>

                                        </div>
                                        <div class="col-md-9 pe-5">
                                            <select name="ddlStatus" class="form-control" id="ddlStatus">
                                                <option value="Active">Active</option>
                                                <option value="InActive">InActive</option>
                                            </select>

                                        </div>
                                    </div>
                                    <hr class="mx-n3">

                                   @*  <div class="row align-items-center py-3">
                                        <div class="col-md-3 ps-5">

                                            <h6 class="mb-0">Product Images</h6>

                                        </div>
                                        <div class="col-md-6 pe-5">
                                            <div class="row" id="ProductImageList">
                                                <div class="col-md-12">
                                                    <input class="form-control imageUpload" type="file" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3 ps-5">
                                            <button type="button" onclick="return AddProductImages();" class="btn btn-primary btn-sm">Add Image</button>
                                        </div>
                                    </div>
                                    <div class="px-5 py-4">
                                        <button type="submit" id="uploadButton" class="btn btn-primary btn-lg">Add Product</button>
                                    </div> *@

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="return CloseModal();">Close</button>
                <button type="button" onclick="return UpdateProduct();" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="txtProductID" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

<script type="text/javascript">
    var ProductLists = [];
    var UserRole = "@HttpContextAccessor.HttpContext.Session.GetString("UserRole")";
    
    $(document).ready(function () {
        $('#btnSearch').click(function () {
            var ObjectData = {
                inventoryType: "Get",
                productId: "",
                name: $("#txtFilterName").val(),
                amount: "",
                brand: $("#txtFilterBrand").val(),
                quantity: "",
                images: []
            };
            makeAjaxRequest(ObjectData);
        });

    });

    function makeAjaxRequest(RequestObject) {
      

        $.ajax({
            url: '@Url.Action("GetProductLists", "Product")',
            method: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(RequestObject),
            success: function (response) {
                // Handle successful response
                console.log(response);
                if (response.isSuccess == true) {
                    BindHtmlData(response.data);
                } else {
                    alert("No Product found");
                    return false;
                }
                return false;
                // Redirect or do something else as needed
            },
            error: function (xhr, status, error) {
                // Handle error
                console.error(xhr.responseText);
                alert('Failed to add product');
            }
        });
    }

    function BindHtmlData(DataLists) {
        var HtmlTableData = "";
        ProductLists = DataLists;
        for (var i = 0; i < DataLists.length; i++) {
            HtmlTableData = HtmlTableData + "<tr>";
            HtmlTableData = HtmlTableData + "<th scope='row'>"+(1+i)+"</th>";
            HtmlTableData = HtmlTableData + "<td>" + DataLists[i].name + "</td>";
            HtmlTableData = HtmlTableData + "<td>" + DataLists[i].amount + "</td>";
            HtmlTableData = HtmlTableData + "<td>" + DataLists[i].quantity + "</td>";
            HtmlTableData = HtmlTableData + "<td>" + DataLists[i].brand + "</td>";
            HtmlTableData = HtmlTableData + "<td>" + DataLists[i].status + "</td>";
            if (UserRole == "Admin") {
                HtmlTableData = HtmlTableData + "<td><i data-toggle='modal' data-target='#updateProductModel' onclick='return CLickEdit(" + DataLists[i].productID + ")' class='fas fa-edit'></i></td>";
            }
            HtmlTableData = HtmlTableData + "</tr>";
        }
        $("#productBodyList").html(HtmlTableData);
    }
    function CLickEdit(ProductID) {

        var filteredProducts = ProductLists.filter(function (product) {
            return product.productID === ProductID;
        });
        $('#updateProductModel').modal('show');
        console.log(filteredProducts);
        $("#txtName").val(filteredProducts[0].name);
        $("#txtAmount").val(filteredProducts[0].amount);
        $("#txtQuantity").val(filteredProducts[0].quantity);
        $("#txtBrand").val(filteredProducts[0].brand);
        $("#txtProductID").val(filteredProducts[0].productID);
        $("#ddlStatus").val(filteredProducts[0].status);
    }
    function CloseModal() {
        $('#updateProductModel').modal('hide');
        return false;
    }

    function UpdateProduct() {

        var RequestObject = {
            InventoryType: "Update",
            ProductId: $("#txtProductID").val(),
            Name: $("#txtName").val(),
            Amount: $("#txtAmount").val(),
            Brand: $("#txtBrand").val(),
            Quantity: $("#txtQuantity").val(),
            Status: $("#ddlStatus").val(),
            Images: []
        };
        console.log(RequestObject);

        $.ajax({
            url: '@Url.Action("AddProduct", "Product")',
            method: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(RequestObject),
            success: function (response) {
                // Handle successful response
                console.log(response);
                if (response.isSuccess) {
                    alert("Product Updated Successfully");
                    CloseModal();
                    $("#btnSearch").click();
                    //window.location.reload();
                } else {
                    CloseModal();
                    alert(response.message);
                    return false;
                }
                // Redirect or do something else as needed
            },
            error: function (xhr, status, error) {
                // Handle error
                console.error(xhr.responseText);
                alert('Failed to add product');
            }
        });

    }

</script>

AssignmentProject_UI/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-9">

            <h1 class="text-white mb-4">Apply for a job</h1>

            <div class="card" style="border-radius: 15px;">
                <div class="card-body">

                    <div class="row align-items-center pt-4 pb-3">
                        <div class="col-md-3 ps-5">

                            <h6 class="mb-0">Name</h6>

                        </div>
                        <div class="col-md-9 pe-5">

                            <input id="txtName" type="text" class="form-control" />

                        </div>
                    </div>

                    <hr class="mx-n3">

                    <div class="row align-items-center py-3">
                        <div class="col-md-3 ps-5">

                            <h6 class="mb-0">Amount</h6>

                        </div>
                        <div class="col-md-9 pe-5">

                            <input id="txtAmount" type="text" class="form-control" />

                        </div>
                    </div>

                    <hr class="mx-n3">

                    <div class="row align-items-center py-3">
                        <div class="col-md-3 ps-5">

                            <h6 class="mb-0">Quantity</h6>

                        </div>
                        <div class="col-md-9 pe-5">
                            <input type="text" id="txtQuantity" class="form-control" />
                        </div>
                    </div>
                    <div class="row align-items-center py-3">
                        <div class="col-md-3 ps-5">

                            <h6 class="mb-0">Brand</h6>

                        </div>
                        <div class="col-md-9 pe-5">

                            <input type="text" id="txtBrand" class="form-control" />

                        </div>
                    </div>
                    <hr class="mx-n3">

                    <div class="row align-items-center py-3">
                        <div class="col-md-3 ps-5">

                            <h6 class="mb-0">Product Images</h6>

                        </div>
                        <div class="col-md-6 pe-5">
                            <div class="row" id="ProductImageList">
                                <div class="col-md-12">
                                    <input class="form-control imageUpload" type="file" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 ps-5">
                            <button type="button" onclick="return AddProductImages();" class="btn btn-primary btn-sm">Add Image</button>
                        </div>
                    </div>
                    <div class="px-5 py-4">
                        <button type="submit" id="uploadButton" class="btn btn-primary btn-lg">Add Product</button>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script type="text/javascript">


    $(document).ready(function () {
        $('#uploadButton').click(function () {
            var imageData = [];
            var totalFiles = $("#ProductImageList > div").length;
            var uploadedFiles = 0;

            $("#ProductImageList > div").each(function (index, element) {
                var $div = $(element);
                var $fileInput = $div.find(".imageUpload");
                if ($fileInput[0].files.length > 0) {
                    var file = $fileInput[0].files[0];
                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        var src = reader.result;
                        var dataObject = {
                            ImageBase64: src.split(',')[1],
                            ImageID: null,
                            Status: "Active",
                        };
                        imageData.push(dataObject);
                        uploadedFiles++;
                        if (uploadedFiles === totalFiles) {
                            // All files processed, make the AJAX call
                            makeAjaxRequest(imageData);
                        }
                    };
                } else {
                    alert("Please upload all the added images");
                    return false;
                }
            });


        });
        $("#ProductImageList").on("click", ".removeBtn", function () {
            $(this).parent().remove(); // Remove parent div when button is clicked
        });

    });
    function AddProductImages() {
        var productDiv = "";
        productDiv = productDiv + "<div class='col-md-12'>";
        productDiv = productDiv + "<input class='form-control imageUpload' type='file' /> <span class='removeBtn' href='#'>Remove</span>";
        productDiv = productDiv + "</div>";
        $("#ProductImageList").append(productDiv);
    };
    function makeAjaxRequest(imageData) {
        var RequestObject = {
            InventoryType: "Add",
            ProductId: null,
            Name: $("#txtName").val(),
            Amount: $("#txtAmount").val(),
            Brand: $("#txtBrand").val(),
            Quantity: $("#txtQuantity").val(),
            Status:"Active",
            Images: imageData
        };
        console.log(RequestObject);

        $.ajax({
            url: '@Url.Action("AddProduct", "Product")',
            method: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(RequestObject),
            success: function (response) {
                // Handle successful response
                console.log(response);
                if (response.isSuccess){
                    alert("Product Added Successfully");
                    window.location.reload();
                } else {
                    //CloseModal();
                    alert(response.message);
                    return false;
                }
                // Redirect or do something else as needed
            },
            error: function (xhr, status, error) {
                // Handle error
                console.error(xhr.responseText);
                alert('Failed to add product');
            }
        });
    }
   
</script>